### ISSUE TITLE
Is Svelte package abandoned?

### ISSUE THREAD

**Issue by demirelio** [brophdawg11/remix-routers#26]
I want to use Remix-like routing and data handling in my Svelte project and run into this project but the last commit was around 10 months ago. Is this project abandoned? @austincrim

**Comment by brophdawg11** [comment]
The `remix-router-svelte` package was more of an alpha POC AFAIK.  There's no active ongoing work because it's functional at the POC level it was aiming for.  Contributions are welcome though to get things updated, but I wouldn't necessarily rely on this for anything besides personal/toy/side projects.
